# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.kernelPackages = pkgs.linuxPackages_6_15;
  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5b513cb6-46c9-4b43-8017-6a3179f3f31b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2bb1905b-5ad3-4a88-a1c3-f7f20938bfcf".device = "/dev/disk/by-uuid/2bb1905b-5ad3-4a88-a1c3-f7f20938bfcf";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E805-FAEB";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/68061873-7824-45f4-ac0d-9da005b00664"; }
    ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.luks.devices."luks-37ca69a6-47c1-46e9-806e-0fe50a57f613".device = "/dev/disk/by-uuid/37ca69a6-47c1-46e9-806e-0fe50a57f613";
  networking.hostName = "pupa"; # Define your hostname.

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;

  # hardware.ipu6.enable = true;
  # hardware.ipu6.platform = "ipu6ep";

  services.hardware.bolt.enable = true;

  services.fprintd.enable = true;
  # services.logind.lidSwitch = "suspend-then-hibernate";
  services.logind.lidSwitch = "suspend";
  services.logind.powerKey = "suspend";
  # systemd.sleep.extraConfig = "HibernateDelaySec=1h";

  services.tlp = {
    enable = true;
    settings = {
      CPU_SCALING_GOVERNOR_ON_AC = "performance";
      CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
    };
  };
}
